apiVersion: application.vtex.dev/v1alpha1
kind: Dependency
metadata:
  name: go-hostname-existing-secret
  namespace: platform-apps
  ownerReferences:
  - apiVersion: application.vtex.dev/v1alpha1
    kind: AppEnvironment
    name: go-hostname-dev
    uid: 11eebad5-0a19-433d-b8d3-52f974fcaf38
    controller: true
spec:
  type: aws-secret-binding
  tags:
    environment: innovation
    owner: platform-core
  values:
    refreshInterval:
      value: 10m
    secretStoreRef:
      value:
        name: vtex
        kind: ClusterSecretStore
    keys:
      value:
      - example-secret
