apiVersion: application.vtex.dev/v1alpha1
kind: Dependency
metadata:
  name: go-hostname-secret-create
  namespace: platform-apps
  ownerReferences:
  - apiVersion: application.vtex.dev/v1alpha1
    kind: AppEnvironment
    name: go-hostname-dev
    uid: 11eebad5-0a19-433d-b8d3-52f974fcaf38
    controller: true
spec:
  type: aws-secret
  tags:
    environment: innovation
    owner: platform-core
  values:
    refreshInterval:
      value: 10m
    secretStore:
      value:
        name: vtex
        kind: ClusterSecretStore
    data:
      value:
        key1: value1
        key2: value2
